# Generated by Django 5.0.6 on 2025-07-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
            },
        ),
    ]
