# Generated by Django 5.0.6 on 2025-07-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmanager',
            name='expo_build_link_android',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versionmanager',
            name='expo_build_link_ios',
            field=models.CharField(default='https://expo.dev/accounts/asmoreira/projects/prospapp_mobile/builds/041c0e80-499d-41fa-b47c-b8954373a11f', max_length=255),
            preserve_default=False,
        ),
    ]
