# Generated by Django 5.0.6 on 2024-06-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('GESTOR', 'Gestor'), ('COLABORADOR', 'Colaborador')], max_length=65, null=True, verbose_name='Perfil'),
        ),
    ]
