# Generated by Django 5.0.6 on 2024-07-16 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profileImage',
            field=models.ImageField(blank=True, default='profiles/default_profile.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='doc_number',
            field=models.CharField(error_messages={'invalid': 'CPF inválido', 'required': 'O campo CPF é obrigatório', 'unique': 'CPF já cadastrado'}, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'E-mail inválido', 'required': 'O campo e-mail é obrigatório', 'unique': 'E-mail já cadastrado'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(error_messages={'required': 'O campo nome é obrigatório', 'unique': 'Nome já cadastrado'}, max_length=125, unique=True, verbose_name='Nome completo'),
        ),
    ]
