# Generated by Django 5.0.6 on 2024-06-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Gestor', 'Gestor'), ('Colaborador', 'Colaborador')], max_length=65, null=True, verbose_name='Perfil'),
        ),
    ]
