# Generated by Django 5.0.6 on 2024-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profileImage',
            field=models.ImageField(blank=True, default='uploads/default_profile.png', null=True, upload_to='uploads/'),
        ),
    ]
