# Generated by Django 5.0.6 on 2024-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='doc_number',
            field=models.BigIntegerField(verbose_name='CPF'),
        ),
    ]
