# Generated by Django 5.0.6 on 2024-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profileImage',
            field=models.ImageField(blank=True, default='profiles/default_profile.png', null=True, upload_to='profiles/'),
        ),
    ]
