# Generated by Django 5.0.6 on 2024-07-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='doc_number',
            field=models.BigIntegerField(unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=125, unique=True, verbose_name='Nome completo'),
        ),
    ]
