# Generated by Django 5.0.6 on 2024-07-07 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_users_doc_number_alter_users_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='doc_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
    ]
