# Generated by Django 5.0.6 on 2025-04-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=145, verbose_name='Nome do local')),
                ('identification_number', models.BigIntegerField(verbose_name='CNPJ')),
                ('workload_hour', models.IntegerField(verbose_name='Carga Horária/Hora')),
                ('workload_minutes', models.IntegerField(verbose_name='Carga Horária/Minutos')),
                ('is_active', models.IntegerField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Local de registro',
                'verbose_name_plural': 'Locais de registro',
            },
        ),
    ]
