# Generated by Django 5.0.6 on 2025-04-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_alter_companypeople_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=145, verbose_name='Nome do local')),
                ('identification_number', models.BigIntegerField(blank=True, null=True, verbose_name='CNPJ')),
                ('workload_hour', models.IntegerField(verbose_name='Carga Horária/Hora')),
                ('workload_minutes', models.IntegerField(verbose_name='Carga Horária/Minutos')),
                ('is_active', models.IntegerField(default=True, verbose_name='Ativa')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Local de registro',
                'verbose_name_plural': 'Locais de registro',
            },
        ),
    ]
