# Generated by Django 5.0.6 on 2025-04-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='workload_hour',
            field=models.IntegerField(default=0, verbose_name='Carga Horária/Hora'),
        ),
        migrations.AlterField(
            model_name='local',
            name='workload_minutes',
            field=models.IntegerField(default=0, verbose_name='Carga Horária/Minutos'),
        ),
    ]
