# Generated by Django 5.0.6 on 2025-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='identification_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='CNPJ'),
        ),
    ]
