# Generated by Django 5.0.6 on 2025-05-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_alter_local_workload_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='workload_hour',
            field=models.IntegerField(default=0, max_length=23, verbose_name='Carga Horária/Hora'),
        ),
        migrations.AlterField(
            model_name='local',
            name='workload_minutes',
            field=models.IntegerField(default=0, max_length=59, verbose_name='Carga Horária/Minutos'),
        ),
    ]
