# Generated by Django 5.0.6 on 2025-05-04 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_alter_local_workload_hour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='workload_hour',
            field=models.IntegerField(default=0, verbose_name='Carga Horária/Hora'),
        ),
        migrations.AlterField(
            model_name='local',
            name='workload_minutes',
            field=models.IntegerField(default=0, verbose_name='Carga Horária/Minutos'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_datetime', models.DateTimeField(verbose_name='Data e hora de entrada')),
                ('exit_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de saída')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point.local', verbose_name='Local/Empresa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de ponto',
                'verbose_name_plural': 'Registros de ponto',
            },
        ),
    ]
