# Generated by Django 5.0.6 on 2025-05-04 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_alter_local_workload_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de registro'),
            preserve_default=False,
        ),
    ]
