# Generated by Django 5.0.6 on 2025-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0005_points_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='local',
            name='limit_radius',
            field=models.FloatField(blank=True, null=True, verbose_name='Rio limite'),
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
