# Generated by Django 5.0.6 on 2025-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0008_points_is_justify_points_justify_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de registro'),
        ),
    ]
