# Generated by Django 5.0.6 on 2025-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0009_alter_points_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='date',
            field=models.DateField(verbose_name='Data de registro'),
        ),
    ]
