# Generated by Django 5.0.6 on 2024-09-21 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Presente')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Cadastro')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='call.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Chamada',
                'verbose_name_plural': 'Chamadas',
            },
        ),
    ]
