# Generated by Django 5.0.6 on 2024-11-11 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 0, 41, 31, 870520, tzinfo=datetime.timezone.utc), verbose_name='Data/Cadastro'),
        ),
    ]
