# Generated by Django 5.0.6 on 2024-11-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_alter_call_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='date',
            field=models.DateField(verbose_name='Data/Cadastro'),
        ),
    ]
