# Generated by Django 5.0.6 on 2025-02-23 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0011_alter_call_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification_number',
            field=models.CharField(error_messages={'invalid': 'CPF inválido', 'required': 'O campo CPF é obrigatório', 'unique': 'CPF já cadastrado'}, max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
    ]
