# Generated by Django 5.0.6 on 2025-02-23 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0012_alter_student_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification_number',
            field=models.CharField(blank=True, error_messages={'invalid': 'CPF inválido', 'required': 'O campo CPF é obrigatório', 'unique': 'CPF já cadastrado'}, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
    ]
