# Generated by Django 5.0.6 on 2025-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0013_alter_student_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_disable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Desativação'),
        ),
    ]
