# Generated by Django 5.0.6 on 2025-08-15 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0014_student_date_disable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classOfStudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='call.classofstudent', verbose_name='Turma')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Professor Turma',
                'verbose_name_plural': 'rofessor Turmas',
                'unique_together': {('classOfStudent', 'user')},
            },
        ),
    ]
