# Generated by Django 5.0.6 on 2025-08-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0015_usersinclass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersinclass',
            unique_together=set(),
        ),
    ]
