# Generated by Django 5.0.6 on 2024-07-16 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.BigIntegerField(verbose_name='CNPJ')),
                ('legal_name', models.CharField(max_length=225, verbose_name='Razão social')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome fantasia')),
                ('slug_name', models.CharField(max_length=25, verbose_name='Apelido')),
                ('logo3', models.ImageField(blank=True, default='companys/logo.png', null=True, upload_to='companys/')),
                ('primary_color3', models.CharField(max_length=7, verbose_name='Cor primária')),
                ('secundary_color3', models.CharField(max_length=7, verbose_name='Cor secundária')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
            },
        ),
        migrations.CreateModel(
            name='CompanyPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Gestor', 'Gestor'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=65, null=True, verbose_name='Perfil')),
                ('is_joined', models.BooleanField(default=False, verbose_name='Ingressou')),
                ('is_pending', models.BooleanField(default=False, verbose_name='Aguardando')),
                ('date_joined', models.DateTimeField(blank=True, null=True, verbose_name='Data/Ingresso')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Relação empresa-colaborador',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
