# Generated by Django 5.0.6 on 2024-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.IntegerField(verbose_name='CNPJ')),
                ('legal_name', models.CharField(max_length=225, verbose_name='Razão social')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome fantasia')),
            ],
        ),
    ]
