# Generated by Django 5.0.6 on 2024-07-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo3',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='primary_color3',
            new_name='primary_color',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='secundary_color3',
            new_name='secundary_color',
        ),
    ]
