# Generated by Django 5.0.6 on 2024-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='identification_number',
            field=models.BigIntegerField(verbose_name='CNPJ'),
        ),
    ]
