# Generated by Django 5.0.6 on 2024-08-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_logo3_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypeople',
            options={'verbose_name': 'Relação empresa-colaborador', 'verbose_name_plural': 'Relação empresa-colaboradores'},
        ),
    ]
