# Generated by Django 5.0.6 on 2024-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypeople',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Ingresso'),
        ),
    ]
