# Generated by Django 5.0.6 on 2025-02-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companypeople_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypeople',
            name='company',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companypeople',
            name='is_joined',
            field=models.BooleanField(default=True, verbose_name='Ingressou'),
        ),
    ]
