# Generated by Django 5.0.6 on 2025-02-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companypeople_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypeople',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companypeople',
            name='is_joined',
            field=models.BooleanField(default=False, verbose_name='Ingressou'),
        ),
    ]
