# Generated by Django 5.0.6 on 2024-06-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companypeople_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypeople',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='Aguardando'),
        ),
    ]
