# Generated by Django 5.0.6 on 2024-07-13 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companypeople_is_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypeople',
            options={'verbose_name': 'Relação empresa-colaborador'},
        ),
        migrations.AlterField(
            model_name='companypeople',
            name='company',
            field=models.ForeignKey(error_messages={'invalid': 'Empresa não encontrada'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companypeople',
            name='role',
            field=models.CharField(blank=True, choices=[('Gestor', 'Gestor'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=65, null=True, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='companypeople',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
