# Generated by Django 5.0.6 on 2024-07-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companypeople_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypeople',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Empresa'),
        ),
    ]
