# Generated by Django 5.0.6 on 2024-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companypeople_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Apelido'),
        ),
    ]
