# Generated by Django 5.0.6 on 2024-07-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug_name',
            field=models.CharField(default=None, max_length=25, verbose_name='Apelido'),
            preserve_default=False,
        ),
    ]
